--1
SELECT * FROM PERSON,DEPARTMENT
SELECT * FROM PERSON CROSS JOIN DEPARTMENT

--2
SELECT P.*,D.DEPARTMENTNAME
FROM PERSON P 
LEFT JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID

--3
SELECT P.*,D.DEPARTMENTNAME,D.DEPARTMENTCODE
FROM PERSON P
LEFT JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID

--4
SELECT P.*,D.DEPARTMENTCODE,D.LOCATION
FROM PERSON P
LEFT JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID

--5
SELECT P.*,D.DEPARTMENTNAME
FROM PERSON P
INNER JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID
WHERE D.DEPARTMENTNAME = 'MECHANICAL'

--6
SELECT P.PERSONNAME,D.DEPARTMENTCODE,P.SALARY
FROM PERSON P
INNER JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID
WHERE CITY = 'AHMEDABAD'

--7
SELECT P.PERSONNAME
FROM PERSON P
INNER JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID
WHERE LOCATION = 'C-BLOCK'

--8
SELECT P.PERSONNAME,P.SALARY,D.DEPARTMENTNAME
FROM PERSON P
INNER JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID
WHERE P.CITY = 'JAMNAGAR'

--9
SELECT P.*
FROM PERSON P
INNER JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID
WHERE JOININGDATE > '1-AUG-2001'

--10
SELECT P.PERSONNAME,DATEDIFF(YEAR,P.JOININGDATE,GETDATE())'EXPERINCE'
FROM PERSON P
LEFT JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID
WHERE DATEDIFF(YEAR,P.JOININGDATE,GETDATE())>25

--11
SELECT D.DEPARTMENTNAME,COUNT(P.PERSONID)AS'COUNT'
FROM PERSON P
RIGHT JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID
GROUP BY DEPARTMENTNAME

--12
SELECT D.DEPARTMENTNAME,MAX(P.SALARY)'MAX SALARY',MIN(P.SALARY)'MIN SALARY'
FROM PERSON P
RIGHT JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID
GROUP BY DEPARTMENTNAME

--13
SELECT CITY,
	SUM(SALARY)'TOTAL SALARY',
	AVG(SALARY)'AVG SALARY',
	MIN(SALARY)'MIN SALARY',
	MAX(SALARY)'MAX SALARY'
FROM PERSON 
GROUP BY CITY

--14
SELECT AVG(SALARY)'AVERAGE SALARY'
FROM PERSON 
WHERE CITY = 'AHMEDABAD'

--15
SELECT CONCAT(P.PERSONNAME,' LIVES IN ',P.CITY,' AND WORKS IN ',D.DEPARTMENTNAME,' DEPARTMENT.')AS DETAILS
FROM PERSON P
LEFT JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID

--16
--DO NOT WORK WITH NULL
--SELECT (P.PERSONNAME + ' EARNS ' + CAST(P.SALARY AS varchar) + ' FROM ' + D.DEPARTMENTNAME + ' DEPARTMENT MONTHLY.') AS DETAILS
SELECT CONCAT(P.PERSONNAME,' EARNS ',P.SALARY,' FROM  ',D.DEPARTMENTNAME,' DEPARTMENT MONTHLY. ')
FROM PERSON P
LEFT JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID

--17
SELECT CITY,
	D.DEPARTMENTNAME,
	SUM(SALARY)'TOTAL SALARY',
	AVG(SALARY)'AVG SALARY',
	MAX(SALARY)'MAX SALARY'
FROM PERSON P
LEFT JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID
GROUP BY CITY,DEPARTMENTNAME

--18
SELECT P.*
FROM PERSON P
LEFT JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID
WHERE P.DEPARTMENTID IS NULL

SELECT P.*
FROM PERSON P
WHERE P.DEPARTMENTID IS NULL

--19
SELECT D.DEPARTMENTNAME,SUM(SALARY)'TOTAL SALARY'
FROM PERSON P 
INNER JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID
GROUP BY D.DEPARTMENTNAME
HAVING SUM(SALARY)>100000

--20
SELECT D.*
FROM DEPARTMENT D
LEFT JOIN PERSON P
ON D.DEPARTMENTID = P.DEPARTMENTID
WHERE P.PERSONID IS NULL

--21
SELECT D.DEPARTMENTNAME,COUNT(PERSONID)AS'TOTAL WORKERS'
FROM DEPARTMENT D
INNER JOIN PERSON P
ON D.DEPARTMENTID = P.DEPARTMENTID
GROUP BY D.DEPARTMENTNAME
HAVING COUNT(PERSONID) > 2

--22
UPDATE PERSON
SET SALARY = SALARY * 1.10
WHERE DEPARTMENTID = (
	SELECT DEPARTMENTID FROM DEPARTMENT
	WHERE DEPARTMENTNAME = 'COMPUTER'
)

SELECT * FROM PERSON
SELECT * FROM DEPARTMENT