--1
SELECT * FROM STUDENT_INFO,RESULT

--2
SELECT * 
FROM STUDENT_INFO 
INNER JOIN RESULT
ON STUDENT_INFO.RNO = RESULT.RNO

--3
SELECT * 
FROM STUDENT_INFO S
LEFT JOIN RESULT R
ON S.RNO = R.RNO

--4
SELECT *
FROM STUDENT_INFO S
RIGHT JOIN RESULT R
ON S.RNO = R.RNO

--5
SELECT *
FROM STUDENT_INFO S
FULL JOIN RESULT R
ON S.RNO = R.RNO

--6
SELECT S.RNO,S.NAME,S.BRANCH,R.SPI
FROM STUDENT_INFO S
LEFT JOIN RESULT R
ON S.RNO = R.RNO

--7
SELECT S.RNO,S.NAME,S.BRANCH,R.SPI
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO = R.RNO
AND S.BRANCH = 'CE'

--8
SELECT S.RNO,S.NAME,S.BRANCH,R.SPI
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO = R.RNO
AND S.BRANCH <> 'EC'

--9
SELECT S.RNO,S.NAME,S.BRANCH,R.SPI
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO = R.RNO
AND R.SPI > 8

--10
SELECT S.RNO,S.NAME,S.BRANCH,R.SPI
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO = R.RNO
AND R.SPI < 8

--11
SELECT BRANCH,AVG(SPI) 'AVG'
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO = R.RNO
GROUP BY S.BRANCH

--12
SELECT BRANCH,AVG(SPI) 'AVG'
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO = R.RNO
AND S.BRANCH IN('CE','ME')
GROUP BY S.BRANCH

--13
SELECT BRANCH,MIN(SPI)'MIN',MAX(SPI)'MAX'
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO = R.RNO
GROUP BY S.BRANCH

--14
SELECT BRANCH,COUNT(S.RNO)'STUDENT COUNT'
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO = R.RNO
GROUP BY BRANCH

--15
SELECT BRANCH,SUM(SPI)'TOTAL SPI'
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO = R.RNO
GROUP BY BRANCH

--16
SELECT BRANCH,COUNT(S.RNO)'TOTAL STUDENT'
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO = R.RNO
AND SPI > 8
GROUP BY BRANCH

--17
SELECT BRANCH,COUNT(S.RNO)'TOTAL STUDENT'
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO = R.RNO
AND SPI < 8
GROUP BY BRANCH

--18
SELECT BRANCH,COUNT(S.RNO)'TOTAL STUDENT'
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO = R.RNO
GROUP BY BRANCH
HAVING AVG(SPI) > 7

--19
SELECT BRANCH,COUNT(RNO)'TOTAL STUDENT'
FROM STUDENT_INFO 
GROUP BY BRANCH
HAVING COUNT(RNO) > 1

--20
SELECT BRANCH,MAX(SPI)'MAX'
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO = R.RNO
GROUP BY BRANCH
HAVING MAX(SPI) > 9

--21
SELECT BRANCH,AVG(SPI)'AVG'
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO = R.RNO
GROUP BY BRANCH
ORDER BY AVG

--22
SELECT BRANCH,MAX(SPI)'AVG'
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO = R.RNO
GROUP BY BRANCH
ORDER BY AVG DESC

--23
SELECT BRANCH,AVG(SPI)'AVG'
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO = R.RNO
GROUP BY BRANCH
ORDER BY AVG

--24
SELECT BRANCH,MAX(SPI)'MAX'
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO = R.RNO
GROUP BY BRANCH
ORDER BY MAX DESC

--25
SELECT BRANCH,MIN(SPI)'MIN',MAX(SPI)'MAX'
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO = R.RNO
GROUP BY BRANCH
HAVING MAX(SPI)-MIN(SPI)>1


SELECT * FROM STUDENT_INFO
SELECT * FROM RESULT