--1
SELECT P.PLAYER_FIRST_NAME,S.Stadium_city
FROM PLAYER P
INNER JOIN TEAM T
ON P.TEAM_ID = T.TEAM_ID
INNER JOIN STADIUM S
ON T.HOME_STADIUM_ID = S.Stadium_id
WHERE S.Stadium_city = 'MUMBAI'

--2
SELECT T.TEAM_NAME,P.PLAYER_FIRST_NAME
FROM TEAM T
INNER JOIN PLAYER P
ON T.TEAM_ID = P.TEAM_ID
ORDER BY T.TEAM_NAME

--3
SELECT P.PLAYER_FIRST_NAME,T.TEAM_WINS,S.Stadium_city
FROM TEAM T
INNER JOIN PLAYER P
ON T.TEAM_ID = P.TEAM_ID
INNER JOIN STADIUM S
ON T.HOME_STADIUM_ID = S.Stadium_id

--4
SELECT T.TEAM_NAME,COUNT(PLAYER_ID) AS 'TOTAL PLAYER'
FROM TEAM T
INNER JOIN PLAYER P
ON T.TEAM_ID = P.TEAM_ID
GROUP BY T.TEAM_NAME

--5
SELECT T.TEAM_NAME,T.TEAM_COACH,
COUNT(PLAYER_ID) AS 'TOTAL BOLWER'
FROM TEAM T
INNER JOIN PLAYER P
ON T.TEAM_ID = P.TEAM_ID
WHERE P.PLAYER_ROLE IN ('BOWLER')
GROUP BY T.TEAM_NAME,T.TEAM_COACH

--6
SELECT T.TEAM_NAME,
SUM(CASE WHEN PLAYER_ROLE = 'BATSMAN' THEN 1 END)'BATSMAN',
SUM(CASE WHEN PLAYER_ROLE = 'BOWLER' THEN 1 END)'BOWLER',
SUM(CASE WHEN PLAYER_ROLE = 'ALL-ROUNDER' THEN 1 END)'ALL-ROUNDER'
FROM TEAM T
INNER JOIN PLAYER P
ON T.TEAM_ID = P.TEAM_ID
GROUP BY T.TEAM_NAME

--7
SELECT S.Stadium_name
FROM STADIUM S
INNER JOIN TEAM T
ON S.Stadium_id = T.HOME_STADIUM_ID
WHERE TEAM_WINS>10

--8
SELECT T.TEAM_NAME,COUNT(PLAYER_ID) AS 'MORE THAN 25 MATCH PLAYED'
FROM TEAM T
INNER JOIN PLAYER P
ON T.TEAM_ID = P.TEAM_ID
WHERE P.PLAYER_MATCHES_PLAYED>25
GROUP BY T.TEAM_NAME

--9
SELECT T.TEAM_NAME,COUNT(PLAYER_ID) AS 'MORE THAN 25 MATCH PLAYED'
FROM TEAM T
INNER JOIN PLAYER P
ON T.TEAM_ID = P.TEAM_ID
WHERE P.PLAYER_JERSEY_NUMBER>30
GROUP BY T.TEAM_NAME

--10
SELECT T.TEAM_NAME,SUM(PLAYER_MATCHES_PLAYED) 'TOTAL MATCHIES PLAYED'
FROM TEAM T
INNER JOIN PLAYER P
ON T.TEAM_ID = P.TEAM_ID
GROUP BY T.TEAM_NAME
ORDER BY T.TEAM_NAME

--11
SELECT S.Stadium_city,COUNT(T.TEAM_ID) AS 'TOTAL TEAM'
FROM STADIUM S
INNER JOIN TEAM T
ON T.HOME_STADIUM_ID = S.Stadium_id
GROUP BY S.Stadium_city

--12
SELECT T.TEAM_NAME,AVG(PLAYER_MATCHES_PLAYED)'AVG OF MATCH PLAYED BY PLAYER'
FROM TEAM T
INNER JOIN PLAYER P
ON T.TEAM_ID = P.TEAM_ID
GROUP BY T.TEAM_NAME

--13
SELECT T.TEAM_NAME,MAX(P.PLAYER_MATCHES_PLAYED) AS 'MAX MATCHES'
FROM TEAM T
INNER JOIN PLAYER P
ON T.TEAM_ID = P.TEAM_ID
GROUP BY T.TEAM_NAME

--14
SELECT T.TEAM_NAME,MIN(P.PLAYER_MATCHES_PLAYED) AS 'MIN MATCHES'
FROM TEAM T
INNER JOIN PLAYER P
ON T.TEAM_ID = P.TEAM_ID
GROUP BY T.TEAM_NAME

--15
SELECT S.Stadium_name,COUNT(PLAYER_ID) AS 'TOTAL PLAYER'
FROM TEAM T
INNER JOIN PLAYER P
ON T.TEAM_ID = P.TEAM_ID
INNER JOIN STADIUM S
ON T.HOME_STADIUM_ID = S.Stadium_id
GROUP BY S.Stadium_name

--16
SELECT T.TEAM_NAME,
COUNT(CASE WHEN P.PLAYER_ROLE='BOWLER' THEN 1 ELSE NULL END)'bowlers',
COUNT(CASE WHEN P.PLAYER_ROLE='all-rounder' THEN 1 ELSE NULL END)'all-rounder'
FROM TEAM T
INNER JOIN PLAYER P
ON T.TEAM_ID = P.TEAM_ID
group by t.TEAM_NAME
having COUNT(CASE WHEN P.PLAYER_ROLE='BOWLER' THEN 1 ELSE NULL END) <
COUNT(CASE WHEN P.PLAYER_ROLE='all-rounder' THEN 1 ELSE NULL END)

--17
SELECT T.TEAM_NAME,MAX(P.PLAYER_MATCHES_PLAYED)-MIN(P.PLAYER_MATCHES_PLAYED) 'DIFF'
FROM TEAM T
INNER JOIN PLAYER P
ON T.TEAM_ID = P.TEAM_ID
GROUP BY T.TEAM_NAME
HAVING MAX(P.PLAYER_MATCHES_PLAYED)-MIN(P.PLAYER_MATCHES_PLAYED) > 5

--18
SELECT S.Stadium_city,SUM(TEAM_WINS) 'TOTAL WIN'
FROM STADIUM S
INNER JOIN TEAM T
ON S.Stadium_id = T.HOME_STADIUM_ID
GROUP BY S.Stadium_city

--19
SELECT T.TEAM_NAME,P.PLAYER_ROLE,
COUNT(P.PLAYER_ID) AS TOTAL_PLAYER
--COUNT(CASE WHEN P.PLAYER_ROLE='BOWLER' THEN 1 ELSE NULL END)'bowlers',
--COUNT(CASE WHEN P.PLAYER_ROLE='all-rounder' THEN 1 ELSE NULL END)'all-rounder',
--COUNT(CASE WHEN P.PLAYER_ROLE='BATSMAN' THEN 1 ELSE NULL END)'batsman'
FROM TEAM T
INNER JOIN PLAYER P
ON T.TEAM_ID = P.TEAM_ID
GROUP BY T.TEAM_NAME,P.PLAYER_ROLE

--20
SELECT T.TEAM_NAME,COUNT(PLAYER_ID)AS 'TOTAL PLAYER START WITH A'
FROM TEAM T
INNER JOIN PLAYER P
ON T.TEAM_ID = P.TEAM_ID
WHERE P.PLAYER_FIRST_NAME LIKE 'A%'
GROUP BY T.TEAM_NAME

SELECT * FROM STADIUM
SELECT * FROM TEAM
SELECT * FROM PLAYER