--1
SELECT * FROM STUDENT
WHERE SPI > (SELECT AVG(SPI) FROM STUDENT)

--2
SELECT * FROM STUDENT
WHERE SPI < (SELECT AVG(SPI) FROM STUDENT)

--3
SELECT * FROM STUDENT
WHERE SPI = (SELECT MAX(SPI) FROM STUDENT)

--4
SELECT * FROM STUDENT
WHERE SPI = (SELECT MIN(SPI) FROM STUDENT)

--5
SELECT * FROM STUDENT
WHERE SPI > (SELECT SPI FROM STUDENT
WHERE SNAME = 'DHARMIK')

--6
SELECT * FROM STUDENT
WHERE SPI < (SELECT SPI FROM STUDENT
WHERE SNAME = 'RIYA')

--7
SELECT * FROM STUDENT
WHERE BRANCH = (SELECT BRANCH FROM STUDENT
WHERE SNAME = 'KRUNAL')

--8
SELECT * FROM STUDENT
WHERE BRANCH NOT IN(SELECT BRANCH FROM STUDENT
WHERE SNAME = 'HETVI')

--9
SELECT * FROM STUDENT
WHERE SPI = (SELECT MAX(SPI) FROM STUDENT
WHERE SPI !=(
SELECT MAX(SPI) FROM STUDENT))

--10
SELECT * FROM STUDENT
WHERE SPI = (SELECT MIN(SPI) FROM STUDENT
WHERE SPI != (SELECT MIN(SPI) FROM STUDENT))

--11
SELECT s1.sname FROM STUDENT S1
WHERE SPI > (
SELECT AVG(SPI) FROM STUDENT S2
WHERE S1.BRANCH = S2.BRANCH
)

--12
SELECT BRANCH FROM STUDENT
WHERE BRANCH = (
	SELECT TOP 1 BRANCH FROM STUDENT
	GROUP BY BRANCH
	ORDER BY AVG(SPI) DESC
)

SELECT BRANCH FROM STUDENT
GROUP BY BRANCH
HAVING AVG(SPI) >= ALL(SELECT AVG(SPI) FROM STUDENT
	GROUP BY BRANCH
)


--13
SELECT * FROM STUDENT
WHERE BRANCH = (
	SELECT TOP 1 BRANCH FROM STUDENT
	GROUP BY BRANCH
	ORDER BY AVG(SPI)
)

SELECT BRANCH FROM STUDENT
GROUP BY BRANCH 
HAVING AVG(SPI) <= ALL(SELECT AVG(SPI) FROM STUDENT
GROUP BY BRANCH)

--14
SELECT * FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO = R.RNO
WHERE SPI > (
SELECT MAX(SPI) FROM STUDENT_INFO S1
INNER JOIN RESULT R1
ON S1.RNO = R1.RNO
WHERE BRANCH = 'ME'
)

SELECT * FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO = R.RNO
WHERE SPI > ALL(
SELECT SPI FROM STUDENT_INFO S1
INNER JOIN RESULT R1
ON S1.RNO = R1.RNO
WHERE BRANCH = 'ME'
)



--15
SELECT * FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO = R.RNO
WHERE SPI < (
SELECT MAX(SPI) FROM STUDENT_INFO S1
INNER JOIN RESULT R1
ON S1.RNO = R1.RNO
WHERE BRANCH = 'ME'
)
AND BRANCH != 'ME'

SELECT * FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO = R.RNO
WHERE SPI < ANY(
SELECT SPI FROM STUDENT_INFO S1
INNER JOIN RESULT R1
ON S1.RNO = R1.RNO
WHERE BRANCH = 'ME'
)
AND BRANCH != 'ME'


--16
SELECT * FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO = R.RNO
WHERE SPI != ALL(
SELECT SPI FROM STUDENT_INFO S1
INNER JOIN RESULT R1
ON S1.RNO = R1.RNO
WHERE BRANCH = 'EC'
)

--17
SELECT * FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO = R.RNO
WHERE SPI > (
SELECT SPI FROM STUDENT_INFO S1
INNER JOIN RESULT R1
ON S1.RNO = R1.RNO
WHERE R1.RNO = 103
)


--18
SELECT * FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO = R.RNO
WHERE SPI > (
SELECT AVG(SPI) FROM STUDENT_INFO S1
INNER JOIN RESULT R1
ON S1.RNO = R1.RNO
WHERE S.BRANCH = S1.BRANCH
)
--19
SELECT * FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO = R.RNO
WHERE SPI > (
SELECT AVG(SPI) FROM STUDENT_INFO S1
INNER JOIN RESULT R1
ON S1.RNO = R1.RNO
WHERE BRANCH = 'CE'
) AND SPI > (
SELECT MAX(SPI) FROM STUDENT_INFO S2
INNER JOIN RESULT R2
ON S2.RNO = R2.RNO
WHERE BRANCH = 'ME'
)

--20
SELECT BRANCH FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO = R.RNO
GROUP BY BRANCH
HAVING AVG(SPI) > (
	SELECT AVG(SPI) FROM RESULT
)

--21
SELECT * FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO = R.RNO
WHERE SPI IN (
 SELECT MAX(SPI) FROM STUDENT_INFO S1
INNER JOIN RESULT R1
ON S1.RNO = R1.RNO
WHERE S.BRANCH = S1.BRANCH
)

--22
SELECT * FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO = R.RNO
WHERE SPI > (
 SELECT AVG(SPI) FROM STUDENT_INFO S1
INNER JOIN RESULT R1
ON S1.RNO = R1.RNO
WHERE S.BRANCH = S1.BRANCH
) AND SPI > (SELECT AVG(SPI) FROM RESULT)


--23
SELECT * FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO = R.RNO
WHERE SPI > ALL(
SELECT MIN(SPI) FROM STUDENT_INFO S1
INNER JOIN RESULT R1
ON S1.RNO = R1.RNO
GROUP BY BRANCH
)

SELECT * FROM STUDENT_INFO S
INNER JOIN RESULT R ON S.RNO = R.RNO
WHERE R.SPI > (
    SELECT MAX(branch_min)
    FROM (
        SELECT MIN(R2.SPI) AS branch_min
        FROM STUDENT_INFO S2 INNER JOIN RESULT R2 ON S2.RNO = R2.RNO
        GROUP BY S2.BRANCH
    ) E
)

--24
SELECT * FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO = R.RNO
WHERE SPI < ALL (
SELECT SPI FROM STUDENT_INFO S1
INNER JOIN RESULT R1
ON S1.RNO = R1.RNO
WHERE BRANCH = 'CE'
)

--25
SELECT DISTINCT BRANCH FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO = R.RNO
WHERE SPI >= (
SELECT MAX(SPI) FROM STUDENT_INFO S1
INNER JOIN RESULT R1
ON S1.RNO = R1.RNO
)

--26
SELECT * FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO = R.RNO
WHERE SPI < ALL(
SELECT SPI FROM STUDENT_INFO S2
INNER JOIN RESULT R2
ON S2.RNO = R2.RNO
WHERE BRANCH = 'CE'
) AND
SPI > ALL(
SELECT SPI FROM STUDENT_INFO S1
INNER JOIN RESULT R1
ON S1.RNO = R1.RNO
WHERE BRANCH = 'ME'
)


SELECT * FROM STUDENT_INFO
SELECT * FROM RESULT

--SELECT * FROM STUDENT
--WHERE SPI > (SELECT MAX(SPI) FROM STUDENT
--WHERE BRANCH = 'EC') AND BRANCH != 'EC'

--SELECT * FROM STUDENT
--WHERE SPI > ALL(SELECT SPI FROM STUDENT WHERE BRANCH = 'EC')
--AND BRANCH != 'EC'

----15
--SELECT * FROM STUDENT
--WHERE SPI < (SELECT MIN(SPI) FROM STUDENT
--WHERE BRANCH = 'EC') AND BRANCH != 'EC'

--SELECT * FROM STUDENT
--WHERE SPI < ANY(SELECT SPI FROM STUDENT WHERE BRANCH = 'EC')
--AND BRANCH != 'EC'

----16
--SELECT * FROM STUDENT
--WHERE SPI != ALL(SELECT SPI FROM STUDENT WHERE BRANCH = 'EC')
--AND BRANCH != 'EC'

----17
--SELECT * FROM STUDENT
--WHERE SPI > (SELECT SPI FROM STUDENT WHERE STDID = 103)

----18
--SELECT * FROM STUDENT S1
--WHERE SPI > (SELECT )

--SELECT * FROM STUDENT
