--1
SELECT MAX(SALARY) 'MIXIMUM',MIN(SALARY) 'MINIMUM'
FROM EMPLOYEE

--2
SELECT SUM(SALARY) 'TOTAL_SAL',AVG(SALARY)'AVERAGE_SAL'
FROM EMPLOYEE

--3
SELECT COUNT(*)'TOTAL EMPLOYEE'
FROM EMPLOYEE

--4
SELECT MAX(SALARY) 'MAXIMUM'
FROM EMPLOYEE
WHERE CITY = 'RAJKOT'

--5
SELECT MAX(SALARY) 'MAXIMUM'
FROM EMPLOYEE
WHERE DEPARTMENT = 'IT'

--6
SELECT COUNT(*) 'TOTAL EMPLOYEE'
FROM EMPLOYEE
WHERE DEPARTMENT = 'HR'

--7
SELECT AVG(SALARY) 'AVERAGE'
FROM EMPLOYEE
WHERE DEPARTMENT = 'ADMIN'

--8
SELECT SUM(SALARY) 'TOTAL SALARY' 
FROM EMPLOYEE
WHERE DEPARTMENT = 'HR'

--9
SELECT COUNT(DISTINCT CITY) 'TOTAL CITY'
FROM EMPLOYEE

--10
SELECT COUNT(DISTINCT DEPARTMENT) 'TOTAL DEPARTMENT'
FROM EMPLOYEE

--11
SELECT MIN(SALARY) 'MINIMUM'
FROM EMPLOYEE
WHERE CITY = 'AHMEDABAD'

--12
SELECT CITY , MAX(SALARY) 'MAXIMUM'
FROM EMPLOYEE
GROUP BY CITY

--13
SELECT DEPARTMENT, MIN(SALARY) 'MINIMUM'
FROM EMPLOYEE
GROUP BY DEPARTMENT

--14
SELECT CITY, MIN(SALARY)'MINIMUM'
FROM EMPLOYEE
GROUP BY CITY

--15
SELECT AVG(SALARY) 'AVERAGE'
FROM EMPLOYEE
WHERE CITY = 'SURAT'

--16
SELECT SUM(SALARY) 'TOTAL SALARY'
FROM EMPLOYEE
WHERE GENDER = 'FEMALE'

--17
SELECT COUNT(*) 'TOTAL MALE'
FROM EMPLOYEE
WHERE GENDER = 'MALE'

--18
SELECT CITY , COUNT(*) 'TOTAL EMPLOYEE'
FROM EMPLOYEE
GROUP BY CITY

--19
SELECT CITY,COUNT(*) 'MALE EMPLOYEE'
FROM EMPLOYEE
WHERE GENDER = 'MALE'
GROUP BY CITY

--20
SELECT DEPARTMENT,MAX(SALARY) 'MAXIMUM'
FROM EMPLOYEE
WHERE CITY <> 'AHMEDABAD'
GROUP BY DEPARTMENT

--21
SELECT CITY,MIN(SALARY) 'MINIMUM'
FROM EMPLOYEE
WHERE GENDER = 'FEMALE'
GROUP BY CITY

--22
SELECT DEPARTMENT,SUM(SALARY) 'TOTAL SALARY'
FROM EMPLOYEE
GROUP BY DEPARTMENT

--23
SELECT AVG(SALARY) 'AVERAGE'
FROM EMPLOYEE
GROUP BY DEPARTMENT

--24
SELECT DEPARTMENT,CITY,COUNT(*) 'TOTAL EMPLOYEE'
FROM EMPLOYEE
GROUP BY DEPARTMENT,CITY

--25
SELECT GENDER,SUM(SALARY)
FROM EMPLOYEE
GROUP BY GENDER

--26
SELECT MAX(SALARY)'MAXIMUM',MIN(SALARY)'MINIMUM'
FROM EMPLOYEE
WHERE GENDER = 'FEMALE'

--27
SELECT DEPARTMENT,CITY,GENDER,AVG(SALARY) 'AVERAE'
FROM EMPLOYEE
GROUP BY DEPARTMENT,CITY,GENDER

--28
SELECT (MAX(SALARY)-MIN(SALARY))'DIFFERENCE'
FROM EMPLOYEE

--29
SELECT DEPARTMENT,SUM(SALARY) 'TOTAL SALARY'
FROM EMPLOYEE
WHERE LEN(DEPARTMENT) = 5
GROUP BY DEPARTMENT

--30
SELECT DEPARTMENT,CITY,MAX(SALARY) 'MAXIMUM'
FROM EMPLOYEE
WHERE CITY LIKE 'R%'
GROUP BY DEPARTMENT,CITY

SELECT * FROM EMPLOYEE