--1
SELECT RANK() OVER(ORDER BY SPI DESC)
AS RANK,*
FROM STUDENT

--2
SELECT DENSE_RANK() OVER(ORDER BY SPI DESC)
AS RANK,*
FROM STUDENT

--3
SELECT ROW_NUMBER() OVER(ORDER BY STDID) AS SNO,
*
FROM STUDENT

--4
SELECT RANK() OVER(PARTITION BY BRANCH ORDER BY SPI DESC) AS RANK,
*
FROM STUDENT

--5
SELECT DENSE_RANK() OVER(PARTITION BY BRANCH ORDER BY SPI DESC)AS RANK,
*
FROM STUDENT

--6
SELECT ROW_NUMBER() OVER(PARTITION BY BRANCH ORDER BY STDID) AS SNO,
*
FROM STUDENT

--7
SELECT SNAME,SPI,LAG(SPI) OVER(ORDER BY SPI,STDID) AS 'PREV_SPI',
ABS(SPI-LAG(SPI) OVER(ORDER BY SPI,STDID))AS DIFF_WITH_PREV
FROM STUDENT

--8
SELECT SNAME,SPI,LEAD(SPI) OVER(ORDER BY SPI DESC,STDID),
ABS(SPI-LEAD(SPI) OVER(ORDER BY SPI DESC,STDID)) AS DIFF_WITH_NEXT
FROM STUDENT

--9
SELECT * FROM (
    SELECT *, DENSE_RANK() OVER (ORDER BY SPI DESC) AS DR
    FROM STUDENT
) T
WHERE DR <= 3

--10
WITH RANK_NO AS(
SELECT *,ROW_NUMBER() OVER(PARTITION BY BRANCH ORDER BY SPI DESC) AS ROW_NUM
FROM STUDENT)
SELECT * FROM RANK_NO
WHERE ROW_NUM <=2

--11
WITH SPI_RANK AS(
SELECT *,DENSE_RANK() OVER(ORDER BY SPI DESC) AS RANK
FROM STUDENT
)
SELECT * FROM SPI_RANK
WHERE RANK = 5

SELECT DISTINCT SPI FROM STUDENT
ORDER BY SPI DESC
OFFSET 4 ROWS
FETCH NEXT 1 ROW ONLY

--12
WITH SPI_RANK AS(
SELECT *,DENSE_RANK() OVER(ORDER BY SPI DESC) AS RANK
FROM STUDENT
)
SELECT * FROM SPI_RANK
WHERE RANK = 6

--13
SELECT * FROM STUDENT S
WHERE SPI IN (SELECT SPI FROM STUDENT GROUP BY SPI HAVING COUNT(SPI)>1)
ORDER BY SPI DESC,STDID

WITH SAME_SPI_COUNT AS(
	SELECT *,
	RANK() OVER(ORDER BY SPI) AS RANK,
	COUNT(*) OVER(PARTITION BY SPI)AS COUNT_SPI
	FROM STUDENT
)
SELECT * FROM SAME_SPI_COUNT
WHERE COUNT_SPI >= 2
ORDER BY SPI DESC,STDID

SELECT DISTINCT S.* FROM STUDENT S
INNER JOIN STUDENT S1
ON S.SPI = S1.SPI
AND S.STDID <> S1.STDID
ORDER BY S.SPI DESC,S.STDID

--14
SELECT SNAME,LAG(SPI) OVER(ORDER BY SPI,STDID) AS 'PREVIOUS SPI',
SPI AS 'CURRENT SPI',
LEAD(SPI) OVER(ORDER BY SPI,STDID) AS 'NEXT SPI'
FROM STUDENT
ORDER BY SPI,STDID

--15
WITH TOPPER_BRANCH AS(
	SELECT *,DENSE_RANK() OVER(PARTITION BY BRANCH ORDER BY SPI DESC) AS RANK
	FROM STUDENT
)
SELECT * FROM TOPPER_BRANCH
WHERE RANK = 1

--16
WITH PREV_NEXT_SPI AS(
	SELECT SNAME,LAG(SPI) OVER(ORDER BY SPI) AS 'PREVIOUS_SPI',
	SPI AS 'CURRENT_SPI',
	LEAD(SPI) OVER(ORDER BY SPI) AS 'NEXT_SPI'
	FROM STUDENT
)
SELECT SNAME,PREVIOUS_SPI,CURRENT_SPI,NEXT_SPI
FROM PREV_NEXT_SPI
WHERE CURRENT_SPI>PREVIOUS_SPI AND CURRENT_SPI<NEXT_SPI
ORDER BY CURRENT_SPI

--17
WITH TOPPER_BRANCH AS(
	SELECT *,DENSE_RANK() OVER(PARTITION BY BRANCH ORDER BY SPI DESC) AS RANK
	FROM STUDENT
)
SELECT * FROM TOPPER_BRANCH
WHERE RANK = 2

--18
WITH RANK_DENSE_RANK AS(
	SELECT *,
	RANK() OVER(ORDER BY SPI DESC) AS 'RANK',
	DENSE_RANK() OVER(ORDER BY SPI DESC) AS 'DENSE'
	FROM STUDENT
)
SELECT * FROM RANK_DENSE_RANK
WHERE RANK <> DENSE
ORDER BY RANK,STDID

--19
WITH NEXT_BRANCH AS(
	SELECT *,LAG(BRANCH) OVER(ORDER BY SPI) AS P_BRANCH,
	LEAD(BRANCH) OVER(ORDER BY SPI) AS N_BRANCH
	FROM STUDENT
)
SELECT * FROM NEXT_BRANCH
WHERE BRANCH = P_BRANCH OR BRANCH = N_BRANCH
ORDER BY SPI

--20
WITH PREV_DIFF AS(
SELECT *,(SPI-LAG(SPI) OVER(ORDER BY STDID)) AS DIFF_PREV
FROM STUDENT
)
SELECT TOP 1 WITH TIES  STDID, SNAME, SPI, DIFF_PREV FROM PREV_DIFF
ORDER BY DIFF_PREV DESC

SELECT * FROM STUDENT
ORDER BY SPI
