--1
SELECT * INTO HIGH_AMOUNT
FROM DEPOSIT
WHERE AMOUNT > 3000

--2
SELECT CNAME, AMOUNT INTO MAVDI_CUSTOMERS
FROM DEPOSIT
WHERE BNAME = 'MAVDI'

--3
SELECT * INTO RECENT_DEPOSITS
FROM DEPOSIT
WHERE ADATE > '2025-01-01'

--4
SELECT DISTINCT BNAME INTO BRANCH_LIST
FROM DEPOSIT

--5
SELECT TOP 5 * INTO TOP_DEPOSIT
FROM DEPOSIT

--6
SELECT * INTO MID_RANGE
FROM DEPOSIT
WHERE AMOUNT BETWEEN 2000 AND 6000

--7
SELECT DISTINCT BNAME AS BRANCH INTO UNIQUE_BRANCH
FROM DEPOSIT

--8
SELECT * INTO NO_BRANCH_ASSIGNED
FROM DEPOSIT
WHERE BNAME IS NULL

--9
SELECT ACTNO,
	   CNAME,
	   BNAME,
	   AMOUNT AS BALANCE,
	   ADATE 
INTO DEPOSIT_COPY
FROM DEPOSIT

--10
SELECT * INTO SELECTED_BRANCH
FROM DEPOSIT
WHERE BNAME IN ('MAVDI','BEDI')

--11
SELECT * INTO STUDENT_BACKUP
FROM STUDENT
WHERE 1<0

--12
SELECT SNAME,CITY INTO CS_STUDENTS
FROM STUDENT
WHERE BRANCH = 'COMPUTER'

--13
SELECT TOP 3 * INTO TOPPER_LIST
FROM STUDENT
ORDER BY SPI DESC

--14
SELECT DISTINCT CITY INTO CITY_LIST
FROM STUDENT

--15
SELECT * INTO MID_STUDENTS
FROM STUDENT
WHERE STDID BETWEEN 103 AND 108

--16
SELECT * INTO NULL_BRANCH_STUDENTS
FROM STUDENT
WHERE BRANCH IS NULL

--17
SELECT STDID,
	   SNAME,
	   CITY,
	   SPI 'PERFORMANCE',
	   BRANCH
INTO STUDENT_COPY
FROM STUDENT

--18
SELECT * INTO CITY_WISE
FROM STUDENT
WHERE CITY IN ('RAJKOT','SURAT')

--19
SELECT * INTO NON_CIVIL_STUDENTS
FROM STUDENT
WHERE BRANCH <> 'CIVIL'

--20
SELECT SNAME,CITY INTO STUDENT_NAME_CITY
FROM STUDENT

