CREATE TABLE ONLINE_CUSTOMER(
	CID INT,
	NAME VARCHAR(50),
	CITY VARCHAR(50)
)

CREATE TABLE OFFLINE_CUSTOMER(
	CID INT,
	NAME VARCHAR(50),
	CITY VARCHAR(50)
)

CREATE TABLE CUSTOMER(
	CID INT,
	NAME VARCHAR(50),
	CITY VARCHAR(50),
	MEMBERSHIP VARCHAR(50),
)

INSERT INTO ONLINE_CUSTOMER
VALUES (101,'RAHUL','RAJKOT'),
(103,'PTIYA','SURAT'),
(106,'DHARMIK','SURAT'),
(107,'MEHUL','MORBI')

INSERT INTO OFFLINE_CUSTOMER
VALUES (102,'AMIT','AHMEDABAD'),
(104,'HETVI','BARODA'),
(105,'RIYA','RAJKOT'),
(106,'DHARMIK','SURAT')

INSERT INTO CUSTOMER
VALUES (101,'RAHUL','RAJKOT','GOLD'),
(102,'AMIT','AHMEDABAD','SILVER'),
(103,'PTIYA','SURAT','GOLD'),
(104,'HETVI','BARODA','PLATINUM'),
(105,'RIYA','RAJKOT','SILVER'),
(106,'DHARMIK','SURAT','GOLD'),
(108,'ISHITA','RAJOT','GOLD')

--1
SELECT NAME FROM ONLINE_CUSTOMER
UNION
SELECT NAME FROM OFFLINE_CUSTOMER

--2
SELECT CITY FROM ONLINE_CUSTOMER
UNION 
SELECT CITY FROM OFFLINE_CUSTOMER

--3
SELECT NAME FROM ONLINE_CUSTOMER
INTERSECT
SELECT NAME FROM OFFLINE_CUSTOMER

--4
SELECT CID FROM ONLINE_CUSTOMER
UNION
SELECT CID FROM OFFLINE_CUSTOMER

--5
SELECT NAME FROM ONLINE_CUSTOMER
UNION
SELECT NAME FROM CUSTOMER
WHERE MEMBERSHIP = 'GOLD'

--6
SELECT NAME FROM CUSTOMER
UNION 
SELECT NAME FROM ONLINE_CUSTOMER

--7
SELECT CITY FROM CUSTOMER
UNION 
SELECT CITY FROM OFFLINE_CUSTOMER

--8
SELECT CID FROM CUSTOMER
UNION ALL
SELECT CID FROM OFFLINE_CUSTOMER
ORDER BY CID

--9
SELECT NAME FROM ONLINE_CUSTOMER
WHERE CITY = 'RAJKOT'
UNION 
SELECT NAME FROM OFFLINE_CUSTOMER
WHERE CITY = 'RAJKOT'
UNION
SELECT NAME FROM CUSTOMER
WHERE CITY = 'RAJKOT'

--10
SELECT NAME FROM ONLINE_CUSTOMER
WHERE NAME LIKE 'R%'
UNION
SELECT NAME FROM OFFLINE_CUSTOMER
WHERE NAME LIKE 'R%'

--11
SELECT NAME FROM ONLINE_CUSTOMER
INTERSECT
SELECT NAME FROM OFFLINE_CUSTOMER

--12
SELECT CID FROM ONLINE_CUSTOMER
INTERSECT
SELECT CID FROM OFFLINE_CUSTOMER

--13
SELECT NAME FROM ONLINE_CUSTOMER
EXCEPT
SELECT NAME FROM OFFLINE_CUSTOMER

--14
SELECT NAME FROM OFFLINE_CUSTOMER
EXCEPT
SELECT NAME FROM ONLINE_CUSTOMER

--15
SELECT CITY FROM ONLINE_CUSTOMER
INTERSECT
SELECT CITY FROM OFFLINE_CUSTOMER

--16
SELECT NAME FROM ONLINE_CUSTOMER
INTERSECT
SELECT NAME FROM CUSTOMER
WHERE MEMBERSHIP = 'GOLD'

--17
SELECT NAME FROM CUSTOMER
WHERE MEMBERSHIP = 'PLATINUM'
EXCEPT
SELECT NAME FROM ONLINE_CUSTOMER

--18
SELECT CID FROM ONLINE_CUSTOMER
EXCEPT
SELECT CID FROM OFFLINE_CUSTOMER

--19
SELECT CID FROM OFFLINE_CUSTOMER
EXCEPT 
SELECT CID FROM ONLINE_CUSTOMER

--20
SELECT NAME FROM CUSTOMER
EXCEPT
SELECT NAME FROM ONLINE_CUSTOMER


--21
SELECT NAME FROM CUSTOMER
WHERE MEMBERSHIP = 'GOLD'
INTERSECT
SELECT NAME FROM OFFLINE_CUSTOMER

--22
SELECT CITY FROM CUSTOMER
UNION
SELECT CITY FROM ONLINE_CUSTOMER
UNION 
SELECT CITY FROM OFFLINE_CUSTOMER

--23
SELECT NAME FROM CUSTOMER
WHERE CITY = 'SURAT'
INTERSECT
SELECT NAME FROM ONLINE_CUSTOMER

--24
SELECT NAME FROM OFFLINE_CUSTOMER
EXCEPT
SELECT NAME FROM CUSTOMER
WHERE CITY = 'RAJKOT'

--25
SELECT NAME FROM CUSTOMER
WHERE MEMBERSHIP = 'GOLD'
AND CITY = 'SURAT'
INTERSECT
SELECT NAME FROM ONLINE_CUSTOMER

--26
(SELECT NAME FROM CUSTOMER INTERSECT SELECT NAME FROM ONLINE_CUSTOMER)
UNION
(SELECT NAME FROM CUSTOMER INTERSECT SELECT NAME FROM OFFLINE_CUSTOMER)
UNION
(SELECT NAME FROM ONLINE_CUSTOMER INTERSECT SELECT NAME FROM OFFLINE_CUSTOMER)

--27
SELECT NAME FROM CUSTOMER
EXCEPT
(SELECT NAME FROM ONLINE_CUSTOMER
INTERSECT
SELECT NAME FROM OFFLINE_CUSTOMER)

--28
SELECT NAME FROM CUSTOMER
WHERE MEMBERSHIP <> 'PLATINUM'
INTERSECT
SELECT NAME FROM ONLINE_CUSTOMER
INTERSECT
SELECT NAME FROM OFFLINE_CUSTOMER

--29
(SELECT NAME FROM ONLINE_CUSTOMER UNION SELECT NAME FROM OFFLINE_CUSTOMER)
EXCEPT
(SELECT NAME FROM ONLINE_CUSTOMER INTERSECT SELECT NAME FROM OFFLINE_CUSTOMER)

--30
SELECT CID FROM CUSTOMER
EXCEPT
(SELECT CID FROM ONLINE_CUSTOMER
UNION
SELECT CID FROM OFFLINE_CUSTOMER)

SELECT CID FROM CUSTOMER
EXCEPT
SELECT CID FROM ONLINE_CUSTOMER
EXCEPT
SELECT CID FROM OFFLINE_CUSTOMER
