--1
SELECT B.TITLE,A.AUTHORNAME
FROM BOOK B
INNER JOIN AUTHOR A
ON B.AUTHORID = A.AUTHORID

--2
SELECT B.TITLE,P.PUBLISHERNAME
FROM BOOK B
INNER JOIN PUBLISHER P
ON B.PUBLISHERID = P.PUBLISHERID

--3
SELECT B.TITLE,A.AUTHORNAME,P.PUBLISHERNAME
FROM BOOK B
INNER JOIN AUTHOR A
ON B.AUTHORID = A.AUTHORID
INNER JOIN PUBLISHER P
ON B.PUBLISHERID = P.PUBLISHERID

--4
SELECT A.AUTHORNAME,P.PUBLISHERNAME,B.PRICE
FROM BOOK B
INNER JOIN PUBLISHER P
ON B.PUBLISHERID = P.PUBLISHERID
INNER JOIN AUTHOR A
ON A.AUTHORID = B.AUTHORID
WHERE PUBLICATIONYEAR > 2010

--5
SELECT A.AUTHORNAME,
	COUNT(BOOKID) AS'TOTAL BOOK'
FROM AUTHOR A
LEFT JOIN BOOK B
ON B.AUTHORID = A.AUTHORID
GROUP BY A.AUTHORNAME

--6
SELECT P.PUBLISHERNAME,SUM(PRICE)AS'TOTAL BOOK PRICE'
FROM PUBLISHER P
INNER JOIN BOOK B
ON B.PUBLISHERID = P.PUBLISHERID
GROUP BY P.PUBLISHERNAME

--7
SELECT A.AUTHORNAME,COUNT(B.BOOKID) AS 'TOTAL BOOKS WRITEN'
FROM AUTHOR A
LEFT JOIN BOOK B
ON A.AUTHORID = B.AUTHORID
GROUP BY AUTHORNAME
HAVING COUNT(BOOKID) = 0

--8
SELECT A.AUTHORNAME,
COUNT(B.BOOKID) AS 'TOTAL BOOKS WRITEN',
AVG(PRICE) 'AVG PRICE'
FROM AUTHOR A
LEFT JOIN BOOK B
ON A.AUTHORID = B.AUTHORID
GROUP BY AUTHORNAME

--9
SELECT P.PUBLISHERNAME,COUNT(BOOKID)AS'TOTAL BOOKS'
FROM PUBLISHER P
LEFT JOIN BOOK B
ON P.PUBLISHERID = B.PUBLISHERID
GROUP BY PUBLISHERNAME
ORDER BY COUNT(BOOKID) DESC

--10
SELECT PUBLICATIONYEAR,COUNT(BOOKID)AS'TOTAL BOOK PUBLISHED'
FROM BOOK
GROUP BY PUBLICATIONYEAR



SELECT * FROM PUBLISHER
SELECT * FROM AUTHOR
SELECT * FROM BOOK
