--1
select cast(GETDATE() as date) 'today_date'
select cast(GETDATE() as time) 'today_date'
select CONVERT(date,SYSDATETIME(),107)
select CONVERT(time,SYSDATETIME(),107)

--2
select GETDATE() + 365

--3
select FORMAT(GETDATE(),'MMM dd yyyy hh:mmtt')

--4
select FORMAT(GETDATE(),'dd MMM yyyy')

--5
select FORMAT(GETDATE(),'MMM dd, yy') 

--6
select DATEDIFF(MONTH,'31-dec-08','31-mar-09')

--7
select DATEDIFF(HOUR,'25-jan-12 7:00','26-jan-12 10:30')

--8
select day('12-may-16'),MONTH('12-may-16'),YEAR('12-may-16')

--9
select GETDATE()+YEAR(5)
SELECT DATEADD(YEAR,+5,GETDATE())

--10
SELECT GETDATE() + MONTH(2)
SELECT DATEADD(MONTH,-2,GETDATE())
SELECT EOMONTH(GETDATE(),-2)

--11
SELECT DATENAME(MONTH,GETDATE())
SELECT DATEPART(MONTH,GETDATE())
SELECT DATENAME(DAY,GETDATE())
SELECT DATEPART(DAY,GETDATE())

--12
SELECT EOMONTH(GETDATE())

--13
SELECT DATEDIFF(YEAR,'02-07-2006',GETDATE())
SELECT DATEDIFF(DAY,'02-07-2006',GETDATE())
SELECT DATEDIFF(MONTH,'02-07-2006',GETDATE())

--14
SELECT * FROM DEPOSIT
WHERE YEAR(ADATE) = 2025 		 

--15
SELECT * FROM DEPOSIT
WHERE FORMAT(ADATE,'MMMM') = 'MAY'

--16
SELECT * FROM DEPOSIT
WHERE ADATE > '01-JAN-2025'

--17
SELECT * FROM DEPOSIT
WHERE ADATE < '01-JAN-2025'

--18
SELECT * FROM DEPOSIT
WHERE FORMAT(ADATE,'dd') = 1

--19
SELECT * FROM DEPOSIT
WHERE FORMAT(ADATE,'MM') > 6

--20
SELECT * FROM DEPOSIT
WHERE YEAR(ADATE) = 2026

--21
SELECT YEAR(ADATE),COUNT(*) FROM DEPOSIT
GROUP BY YEAR(ADATE)

--22
SELECT MONTH(ADATE),COUNT(*) FROM DEPOSIT
GROUP BY MONTH(ADATE)

--23
SELECT MAX(AMOUNT),YEAR(ADATE)
FROM DEPOSIT
GROUP BY YEAR(ADATE)

--24
SELECT MIN(AMOUNT),MONTH(ADATE)
FROM DEPOSIT
GROUP BY MONTH(ADATE)

--25
SELECT SUM(AMOUNT),YEAR(ADATE)
FROM DEPOSIT
GROUP BY YEAR(ADATE)

--26
SELECT * 
FROM DEPOSIT
WHERE ADATE BETWEEN '01-MAR-2025' AND '31-DEC-2025'

--27
SELECT * FROM DEPOSIT
WHERE DAY(ADATE) = FORMAT(ADATE,'yy')

--28
SELECT DATEDIFF(DAY,Adate,GETDATE()) from DEPOSIT

SELECT * FROM DEPOSIT


