--1
SELECT CITY
FROM EMPLOYEE
GROUP BY CITY
HAVING SUM(SALARY) > 20000

--2
SELECT DEPARTMENT
FROM EMPLOYEE
GROUP BY DEPARTMENT
HAVING AVG(SALARY) > 12000

--3
SELECT DEPARTMENT
FROM EMPLOYEE
GROUP BY DEPARTMENT
HAVING SUM(SALARY) > 20000

--4
SELECT DEPARTMENT
FROM EMPLOYEE
GROUP BY DEPARTMENT
HAVING COUNT(*)>2

--5
SELECT CITY
FROM EMPLOYEE
GROUP BY CITY
HAVING MIN(SALARY) < 7000

--6
SELECT CITY
FROM EMPLOYEE
GROUP BY CITY
HAVING AVG(SALARY) < 12000

--7
SELECT DEPARTMENT
FROM EMPLOYEE
GROUP BY DEPARTMENT
HAVING MAX(SALARY) > 14000

--8
SELECT CITY
FROM EMPLOYEE
GROUP BY CITY
HAVING SUM(SALARY) > 30000

--9
SELECT DEPARTMENT
FROM EMPLOYEE
GROUP BY DEPARTMENT
HAVING COUNT(*) = 2

--10
SELECT CITY
FROM EMPLOYEE
WHERE GENDER = 'FEMALE'
GROUP BY CITY
HAVING COUNT(*) >= 1

--11
SELECT DEPARTMENT 
FROM EMPLOYEE
WHERE GENDER = 'MALE'
GROUP BY DEPARTMENT
HAVING MIN(SALARY) > 7000

--12
SELECT CITY
FROM EMPLOYEE
WHERE GENDER = 'FEMALE'
GROUP BY CITY
HAVING MAX(SALARY) >13000

--13
SELECT DEPARTMENT
FROM EMPLOYEE
GROUP BY DEPARTMENT
HAVING AVG(SALARY) BETWEEN 10000 AND 14000

--14
SELECT CITY,COUNT(EID)'NUMBER EMPLOYEE'
FROM EMPLOYEE
WHERE YEAR(JOININGYEAR) < 2023
GROUP BY CITY
HAVING COUNT(EID) > 1

--15
SELECT CITY
FROM EMPLOYEE
WHERE GENDER = 'MALE'
GROUP BY CITY
HAVING SUM(SALARY) > 15000

--16
SELECT DEPARTMENT,MAX(SALARY)'MAXIMUM'
FROM EMPLOYEE
GROUP BY DEPARTMENT
HAVING MAX(SALARY) > 13000
ORDER BY MAX(SALARY)

--17
SELECT CITY
FROM EMPLOYEE
WHERE GENDER = 'MALE'
GROUP BY CITY
HAVING SUM(SALARY) > 15000

--18
SELECT DEPARTMENT 
FROM EMPLOYEE
WHERE YEAR(JOININGYEAR) > 2022
GROUP BY DEPARTMENT
HAVING COUNT(*) > 1

--19
SELECT DEPARTMENT 
FROM EMPLOYEE
WHERE GENDER = 'FEMALE'
GROUP BY DEPARTMENT
HAVING AVG(SALARY) > 8000

--20
SELECT DEPARTMENT
FROM EMPLOYEE
GROUP BY DEPARTMENT
HAVING SUM(SALARY) BETWEEN 20000 AND 40000

--21
SELECT DEPARTMENT
FROM EMPLOYEE
WHERE YEAR(JOININGYEAR) > 2021
GROUP BY DEPARTMENT
HAVING SUM(SALARY) > 20000

--22
SELECT CITY
FROM EMPLOYEE
WHERE YEAR(JOININGYEAR) > 2022
GROUP BY CITY
HAVING AVG(SALARY) > 10000

--23
SELECT CITY
FROM EMPLOYEE
GROUP BY CITY
HAVING COUNT(DISTINCT DEPARTMENT) > 1

--24
SELECT CITY
FROM EMPLOYEE
WHERE YEAR(JOININGYEAR) < 2022
GROUP BY CITY
HAVING MAX(SALARY) > 12000

--25
SELECT DEPARTMENT
FROM EMPLOYEE
WHERE GENDER = 'FEMALE'
GROUP BY DEPARTMENT
HAVING SUM(SALARY) < 15000

--26
SELECT CITY
FROM EMPLOYEE
GROUP BY CITY
HAVING SUM(
CASE
WHEN GENDER = 'MALE' THEN 1
ELSE 0
END) > SUM(CASE WHEN GENDER = 'FEMALE' THEN 1 ELSE 0 END)

--27
SELECT DEPARTMENT 
FROM EMPLOYEE
GROUP BY DEPARTMENT
HAVING COUNT(DISTINCT CITY) > 1

--28
SELECT CITY
FROM EMPLOYEE
WHERE DEPARTMENT <> 'IT'
GROUP BY CITY
HAVING SUM(SALARY) > 15000

--29
SELECT DEPARTMENT 
FROM EMPLOYEE
WHERE DEPARTMENT <> 'HR'
GROUP BY DEPARTMENT
HAVING AVG(SALARY) > 11000

--30
SELECT DEPARTMENT 
FROM EMPLOYEE
GROUP BY DEPARTMENT
HAVING SUM(CASE WHEN GENDER = 'MALE' THEN SALARY ELSE 0 END) > 
	   SUM(CASE WHEN GENDER = 'FEMALE' THEN SALARY ELSE 0 END)

select department
from employee
group by department
having (select sum(salary) from employee e1 where e1.department = employee.department and gender = 'male') >
       (select sum(salary) from employee e1 where e1.department = employee.department and gender = 'female')

SELECT * FROM EMPLOYEE