--1
SELECT B.TITLE,A.AUTHORNAME
FROM BOOK B
INNER JOIN AUTHOR A
ON B.AUTHORID = A.AUTHORID

--2
SELECT B.TITLE,P.PUBLISHERNAME
FROM BOOK B
INNER JOIN PUBLISHER P
ON B.PUBLISHERID = P.PUBLISHERID

--3
SELECT B.TITLE,A.AUTHORNAME,P.PUBLISHERNAME
FROM BOOK B
INNER JOIN AUTHOR A
ON B.AUTHORID = A.AUTHORID
INNER JOIN PUBLISHER P
ON B.PUBLISHERID = P.PUBLISHERID

--4
SELECT A.AUTHORNAME,P.PUBLISHERNAME,B.PRICE
FROM BOOK B
INNER JOIN PUBLISHER P
ON B.PUBLISHERID = P.PUBLISHERID
INNER JOIN AUTHOR A
ON A.AUTHORID = B.AUTHORID
WHERE PUBLICATIONYEAR > 2010

--5
SELECT A.AUTHORNAME,
	COUNT(BOOKID) AS'TOTAL BOOK'
FROM AUTHOR A
LEFT JOIN BOOK B
ON B.AUTHORID = A.AUTHORID
GROUP BY A.AUTHORNAME

--6
SELECT P.PUBLISHERNAME,SUM(PRICE)AS'TOTAL BOOK PRICE'
FROM PUBLISHER P
INNER JOIN BOOK B
ON B.PUBLISHERID = P.PUBLISHERID
GROUP BY P.PUBLISHERNAME

--7
SELECT A.AUTHORNAME,COUNT(B.BOOKID) AS 'TOTAL BOOKS WRITEN'
FROM AUTHOR A
LEFT JOIN BOOK B
ON A.AUTHORID = B.AUTHORID
GROUP BY AUTHORNAME
HAVING COUNT(BOOKID) = 0

--8
SELECT A.AUTHORNAME,
COUNT(B.BOOKID) AS 'TOTAL BOOKS WRITEN',
AVG(PRICE) 'AVG PRICE'
FROM AUTHOR A
LEFT JOIN BOOK B
ON A.AUTHORID = B.AUTHORID
GROUP BY AUTHORNAME

--9
SELECT P.PUBLISHERNAME,COUNT(BOOKID)AS'TOTAL BOOKS'
FROM PUBLISHER P
LEFT JOIN BOOK B
ON P.PUBLISHERID = B.PUBLISHERID
GROUP BY PUBLISHERNAME
ORDER BY COUNT(BOOKID) DESC

--10
SELECT PUBLICATIONYEAR,COUNT(BOOKID)AS'TOTAL BOOK PUBLISHED'
FROM BOOK
GROUP BY PUBLICATIONYEAR

--11
SELECT P.PUBLISHERNAME,SUM(PRICE)AS'TOTAL BOOK PRICE'
FROM PUBLISHER P
INNER JOIN BOOK B
ON B.PUBLISHERID = P.PUBLISHERID
GROUP BY PUBLISHERNAME
HAVING SUM(PRICE) > 500
ORDER BY SUM(PRICE)

--12
SELECT A.AUTHORNAME,MAX(PRICE) AS 'MOST EXPENCIVE BOOK'
FROM AUTHOR A
INNER JOIN BOOK B
ON A.AUTHORID = B.AUTHORID
GROUP BY AUTHORNAME
ORDER BY MAX(PRICE) DESC

--13
SELECT P.PUBLISHERNAME,MAX(PRICE)-MIN(PRICE) AS 'DIFF'
FROM PUBLISHER P
INNER JOIN BOOK B
ON P.PUBLISHERID = B.PUBLISHERID
GROUP BY PUBLISHERNAME

--14
SELECT P.PUBLISHERNAME,PUBLICATIONYEAR,SUM(PRICE) AS 'BOOK PRICE'
FROM PUBLISHER P
INNER JOIN BOOK B
ON P.PUBLISHERID = B.PUBLISHERID
GROUP BY PUBLISHERNAME,PUBLICATIONYEAR
ORDER BY PUBLISHERNAME

--15
SELECT A.AUTHORNAME,SUM(PRICE) AS 'BOOKS PRICE'
FROM AUTHOR A
INNER JOIN BOOK B
ON A.AUTHORID = B.AUTHORID
GROUP BY A.AUTHORNAME
ORDER BY SUM(PRICE) DESC


CREATE TABLE EMPLOYEE_MASTER
(
	EMPLOYEENO VARCHAR(10),
	NAME VARCHAR(50),
	MANAGERNO VARCHAR(10)
)

INSERT INTO EMPLOYEE_MASTER
VALUES('E01','TARUN',NULL),
('E02','ROHAN','E02'),
('E03','PRIYA','E01'),
('E04','MILAN','E03'),
('E05','JAY','E01'),
('E06','ANJANA','E04')

--16
SELECT E.NAME 'EMPLOYEE NAME',
	   M.NAME 'MANAGER NAME'
FROM EMPLOYEE_MASTER E
LEFT JOIN EMPLOYEE_MASTER M
ON E.MANAGERNO=M.EMPLOYEENO

--17
SELECT DISTINCT M.NAME
FROM EMPLOYEE_MASTER E
INNER JOIN EMPLOYEE_MASTER M
ON E.MANAGERNO = M.EMPLOYEENO

--18
SELECT M.NAME,COUNT(E.NAME) 'TOTAL EMPLOYEE'
FROM EMPLOYEE_MASTER E
INNER JOIN EMPLOYEE_MASTER M
ON E.MANAGERNO = M.EMPLOYEENO
GROUP BY M.NAME

--19
SELECT E.NAME'EMPLOYEE',M.NAME'MANEGER',S.NAME'SENIOR MANAGER'
FROM EMPLOYEE_MASTER E
LEFT JOIN EMPLOYEE_MASTER M
ON E.MANAGERNO = M.EMPLOYEENO
LEFT JOIN EMPLOYEE_MASTER S
ON M.MANAGERNO = S.EMPLOYEENO

--20
SELECT M.NAME,COUNT(E.EMPLOYEENO) AS 'TOTAL EMPLOYEE'
FROM EMPLOYEE_MASTER E
INNER JOIN EMPLOYEE_MASTER M
ON E.MANAGERNO = M.EMPLOYEENO
GROUP BY M.NAME
ORDER BY COUNT(E.EMPLOYEENO) DESC

SELECT * FROM EMPLOYEE_MASTER

SELECT * FROM PUBLISHER
SELECT * FROM AUTHOR
SELECT * FROM BOOK
