--1
SELECT * FROM EMPLOYEE
WHERE FIRSTNAME LIKE 'H%'

--2
SELECT * FROM EMPLOYEE
WHERE LEN(FIRSTNAME) = 5

--3
SELECT * FROM EMPLOYEE
WHERE CITY LIKE '_____T'

--4
SELECT * FROM EMPLOYEE
WHERE LASTNAME LIKE '%EL'

--5
SELECT * FROM EMPLOYEE
WHERE FIRSTNAME LIKE 'R%A'

--6
SELECT * FROM EMPLOYEE
WHERE FIRSTNAME LIKE 'V_S%'

--7
SELECT * FROM EMPLOYEE
WHERE CITY IS NULL AND FIRSTNAME LIKE '______'

--8
SELECT * FROM EMPLOYEE
WHERE FIRSTNAME LIKE '%[A]%[R]%'

--9
SELECT * FROM EMPLOYEE
WHERE CITY LIKE '[RB]%'

--10
SELECT * FROM EMPLOYEE
WHERE DEPARTMENT IS NOT NULL

--11
SELECT * FROM EMPLOYEE
WHERE FIRSTNAME LIKE '[A-H]%'

--12
SELECT * FROM EMPLOYEE
WHERE FIRSTNAME LIKE '_[AEIOU]%'

--13
SELECT * FROM EMPLOYEE
WHERE LEN(FIRSTNAME) >= 5

--14
SELECT * FROM EMPLOYEE
WHERE LASTNAME LIKE '[P][A]%'

--15
SELECT * FROM EMPLOYEE
WHERE CITY LIKE '[^B]%'

--16
SELECT * FROM EMPLOYEE
WHERE FIRSTNAME LIKE '_[^AEIOU]%'

--17
SELECT * FROM EMPLOYEE
WHERE YEAR(JOININGYEAR) LIKE '___[46]'

--18
SELECT * FROM EMPLOYEE
WHERE FIRSTNAME LIKE 'H%I' AND CITY LIKE '%R%A%'

--19
SELECT * FROM EMPLOYEE
WHERE FIRSTNAME LIKE '%A%' 
	  AND CITY LIKE '%D' 
	  AND DEPARTMENT IS NOT NULL

--20
SELECT * FROM EMPLOYEE
WHERE FIRSTNAME LIKE '_[AEIOU][AEIOU]%' AND CITY LIKE 'R%'

--21
SELECT * FROM EMPLOYEE
WHERE CITY LIKE '%R%A%' 
	  AND SALARY < 13000
	  AND YEAR(JOININGYEAR) LIKE '___6'

--22
SELECT * FROM EMPLOYEE
WHERE SALARY BETWEEN 10000 AND 15000 
	  AND CITY LIKE '%K%O%' 
	  AND FIRSTNAME LIKE 'H%'

--23
SELECT * FROM EMPLOYEE
WHERE FIRSTNAME LIKE '[AD]%' 
	  AND SALARY > 12000

--24
SELECT * FROM EMPLOYEE
WHERE CITY LIKE '%N%'
	  AND SALARY < 15000

--25
SELECT * FROM EMPLOYEE
WHERE LEN(FIRSTNAME) = 6
	  AND CITY LIKE '%[AR]'

--26
SELECT * FROM EMPLOYEE
WHERE FIRSTNAME LIKE '%[AEIOU]'
	  AND DEPARTMENT LIKE '[AEIOU]%'
	  AND SALARY BETWEEN 10000 AND 15000

--27
SELECT * FROM EMPLOYEE
WHERE LASTNAME LIKE '%A%A%'
	  AND GENDER = 'MALE'
	  AND SALARY <> 14000

--28
SELECT * FROM EMPLOYEE
WHERE FIRSTNAME LIKE '_[AEIOU]%'
	  AND LASTNAME LIKE '%R'
	  AND SALARY < 12000

--29
SELECT * FROM EMPLOYEE
WHERE CITY IS NOT NULL 
	  AND FIRSTNAME LIKE '[^AEIOU]%'
	  AND DEPARTMENT NOT IN ('HR','IT')

--30
SELECT * FROM EMPLOYEE
WHERE CITY IS NOT NULL
	  AND FIRSTNAME LIKE '%[AEIOU]'
	  AND DEPARTMENT NOT IN ('HR','IT')

SELECT * FROM EMPLOYEE
