--1
ALTER TABLE DEPOSIT
ADD STATE VARCHAR(20) NULL

--2
ALTER TABLE DEPOSIT
ADD PINCODE INT NULL,CITY VARCHAR(20) NULL

--3
ALTER TABLE DEPOSIT
ALTER COLUMN CNAME VARCHAR(35)

--4
ALTER TABLE DEPOSIT
ALTER COLUMN AMOUNT INT 

--5
ALTER TABLE DEPOSIT
DROP COLUMN CITY

--6
EXEC SP_RENAME 'DEPOSIT_DETAIL.ACTNO','ANO'

--7
EXEC SP_RENAME 'DEPOSIT.BNAME','BRANCH_NAME'

--8
EXEC SP_RENAME 'DEPOSIT','DEPOSIT_DETAIL'

--9
ALTER TABLE DEPOSIT_DETAIL
ADD IFSC_CODE VARCHAR(15) NULL

--10
ALTER TABLE DEPOSIT_DETAIL
ALTER COLUMN BRANCH_NAME VARCHAR(30)

--11
EXEC SP_RENAME 'DEPOSIT_DETAIL.ADATE','AOPENDATE'

--12
ALTER TABLE DEPOSIT_DETAIL
DROP COLUMN AOPENDATE

--13
EXEC SP_RENAME 'DEPOSIT_DETAIL.CNAME','CUSTOMER_NAME'

--14
ALTER TABLE DEPOSIT_DETAIL
ADD COUNTRY VARCHAR(20)

--15
ALTER TABLE DEPOSIT_DETAIL
ADD ACCOUNT_TYPE VARCHAR(15)

--16
ALTER TABLE DEPOSIT_DETAIL
ALTER COLUMN PINCODE BIGINT NULL

--17
ALTER TABLE DEPOSIT_DETAIL
DROP COLUMN ACCOUNT_TYPE

--18
EXEC SP_RENAME 'DEPOSIT_DETAIL.AMOUNT','BALANCE'

--19
ALTER TABLE DEPOSIT_DETAIL
ADD STATUS VARCHAR(10)

--20
EXEC SP_RENAME 'DEPOSIT_DETAIL','BANK_DEPOSIT'


/*PART - B*/

--1
DELETE FROM BANK_DEPOSIT
WHERE BALANCE <= 3000 

--2
DELETE FROM BANK_DEPOSIT
WHERE BRANCH_NAME = 'BEDI'

--3
DELETE FROM BANK_DEPOSIT
WHERE ANO > 102 AND ANO < 109

--4
DELETE FROM BANK_DEPOSIT
WHERE BRANCH_NAME IN ('BEDI','MADHAPAR')

--5
DELETE FROM BANK_DEPOSIT
WHERE BALANCE = 8000

--6
DELETE FROM BANK_DEPOSIT
WHERE BRANCH_NAME IS NULL

--7
DELETE FROM BANK_DEPOSIT
WHERE BALANCE = 7000 AND 
	  CUSTOMER_NAME = 'CHARMI' AND 
	  BRANCH_NAME = 'SHITAL PARK'

--8
DELETE FROM BANK_DEPOSIT

--9
TRUNCATE TABLE BANK_DEPOSIT

--10
DROP TABLE BANK_DEPOSIT

--PART - B
--1
DELETE FROM STUDENT
WHERE STDID > 105

--2
DELETE FROM STUDENT
WHERE BRANCH IS NULL AND SNAME IS NOT NULL

--3
DELETE FROM STUDENT
WHERE SPI < 9 AND CITY = 'RAJKOT'

--4
DELETE FROM STUDENT
WHERE BRANCH IS NOT NULL

--5
TRUNCATE TABLE STUDENT

SELECT * FROM STUDENT

