USE MCA_123

--1
CREATE VIEW EMPLOYEE_ALL
AS 
SELECT * FROM EMPLOYEE

SELECT * FROM EMPLOYEE_ALL

--2
CREATE VIEW EMPLOYEE_NAMEDEPTSALARY
AS
SELECT FIRSTNAME,DEPARTMENT,SALARY
FROM EMPLOYEE

--3
CREATE VIEW EMPLOYEE_BASIC
AS
SELECT EID,FIRSTNAME,CITY
FROM EMPLOYEE

SELECT * FROM EMPLOYEE_BASIC

--4
CREATE VIEW IT_EMPLOYEE
AS
SELECT * FROM EMPLOYEE
WHERE DEPARTMENT = 'IT'

--5
CREATE VIEW HR_EMPLOYEE
AS
SELECT * FROM EMPLOYEE
WHERE DEPARTMENT = 'HR'

--6
CREATE VIEW EMPLOYEE_2026
AS
SELECT * FROM EMPLOYEE
WHERE YEAR(JOININGYEAR) = 2026

--7
CREATE VIEW PATEL_EMPLOYEE
AS
SELECT * FROM EMPLOYEE
WHERE LASTNAME = 'PATEL'

--8
CREATE VIEW HIGH_SALARY_EMP
AS
SELECT * FROM EMPLOYEE
WHERE SALARY > 12000

--9
CREATE VIEW EMPLOYEE_WITH_ABOVE_14000_SALARY
AS
SELECT * FROM EMPLOYEE
WHERE SALARY > 14000

--10
CREATE VIEW LOW_SALARY_EMP
AS
SELECT * FROM EMPLOYEE
WHERE SALARY < 10000

--11
CREATE VIEW SERVER_DEPT
AS
SELECT * FROM EMPLOYEE
WHERE DEPARTMENT = 'SERVER'

--12
INSERT INTO EMPLOYEE_BASIC
VALUES(112,'MEET','SURAT')

SP_HELP EMPLOYEE

--13
UPDATE EMPLOYEE_NAMEDEPTSALARY
SET DEPARTMENT = 'IT'
WHERE FIRSTNAME = 'DEEP'

--14
DELETE FROM EMPLOYEE_BASIC
WHERE EID = 107

--15
DROP VIEW IT_EMPLOYEE

--16
CREATE VIEW ADMIN_EMPLOYEES
AS
SELECT * FROM EMPLOYEE
WHERE DEPARTMENT = 'ADMIN'

--17
CREATE VIEW FEMALE_EMPLOYEES
AS
SELECT * FROM EMPLOYEE
WHERE GENDER = 'FEMALE'

--18
CREATE VIEW MALE_EMPLOYEES
AS
SELECT * FROM EMPLOYEE
WHERE GENDER = 'MALE'

--19
CREATE VIEW RAJKOT_EMPLOYEES
AS
SELECT * FROM EMPLOYEE
WHERE CITY = 'RAJKOT'

--20
CREATE VIEW AHMEDABAD_EMPLOYEES
AS
SELECT * FROM EMPLOYEE
WHERE CITY = 'AHMEDABAD'

--21
CREATE VIEW SALARY_BETWEEN_10000_14000
AS
SELECT * FROM EMPLOYEE
WHERE SALARY BETWEEN 10000 AND 14000

--22
CREATE VIEW RECENT_EMPLOYEES
AS
SELECT * FROM EMPLOYEE
WHERE JOININGYEAR > '2023'

--23
CREATE VIEW OLD_EMPLOYEES
AS
SELECT * FROM EMPLOYEE
WHERE YEAR(JOININGYEAR) < 2023

--24
CREATE VIEW EMPLOYEES_START_R
AS
SELECT * FROM EMPLOYEE
WHERE FIRSTNAME LIKE 'R%'

--25
CREATE VIEW EMPLOYEES_END_A
AS
SELECT * FROM EMPLOYEE
WHERE FIRSTNAME LIKE '%A'

--26
CREATE VIEW EMPLOYEES_NAMECONTAINS_H
AS
SELECT * FROM EMPLOYEE
WHERE FIRSTNAME LIKE '%H%'

--27
CREATE VIEW EMPLOYEES_NAMECONTAINS_VOWELS
AS 
SELECT * FROM EMPLOYEE
WHERE FIRSTNAME LIKE '%[AEIOU]%'

--28
CREATE VIEW FOURLETTER_NAME
AS
SELECT EID,FIRSTNAME,DEPARTMENT
FROM EMPLOYEE
WHERE LEN(FIRSTNAME) = 4

--29
CREATE VIEW EMPLOYEES_START_M_END_N
AS
SELECT * FROM EMPLOYEE
WHERE FIRSTNAME LIKE 'M%N'

--30
CREATE VIEW TRANSPORT_DEPT
AS
SELECT * FROM EMPLOYEE
WHERE DEPARTMENT = 'TRANSPORT'

SELECT * FROM EMPLOYEE
SELECT * FROM EMPLOYEE_BASIC