CREATE DATABASE MCA_123

USE MCA_123

CREATE TABLE STUDENT_INFO
(
	RNO INT PRIMARY KEY IDENTITY(101,1),
	NAME VARCHAR(20) NOT NULL,
	BRANCH VARCHAR(20) DEFAULT('CE')
)

CREATE TABLE RESULT
(
	RESULTID INT IDENTITY(11,1),
	SPI DECIMAL(4,2) CHECK(SPI BETWEEN 0 AND 10),
	RNO INT,

	CONSTRAINT PK_RESULT_RESULTID
	PRIMARY KEY (RESULTID),

	CONSTRAINT FK_RESULT_RNO
	FOREIGN KEY(RNO) REFERENCES STUDENT_INFO(RNO)
)

INSERT INTO STUDENT_INFO(NAME)
VALUES ('RAJU'),
('AMIT')

INSERT INTO STUDENT_INFO(NAME,BRANCH)
VALUES('SANJAY','ME'),
('NEHA','EC'),
('MEERA','EE'),
('MAHESH','ME')

SELECT * FROM STUDENT_INFO

INSERT INTO RESULT(SPI,RNO)
VALUES(8.8,101),
(9.2,102),
(7.6,103),
(8.2,104),
(7.0,105),
(8.9,106)

SELECT * FROM RESULT

CREATE TABLE DEPARTMENT
(
	DEPARTMENTID INT PRIMARY KEY IDENTITY(1,1),
	DEPARTMENTNAME VARCHAR(100) NOT NULL UNIQUE,
	DEPARTMENTCODE VARCHAR(50) NOT NULL UNIQUE,
	LOCATION VARCHAR(50) NOT NULL
)

CREATE TABLE PERSON
(
	PERSONID INT PRIMARY KEY IDENTITY(101,1),
	PERSONNAME VARCHAR(100) NOT NULL,
	DEPARTMENTID INT,
	SALARY DECIMAL(8,2) NOT NULL,
	JOININGDATE DATETIME NOT NULL,
	CITY VARCHAR(100) NOT NULL,

	CONSTRAINT FK_DEPARTMENT_DEPARTMENTID
	FOREIGN KEY(DEPARTMENTID) REFERENCES DEPARTMENT(DEPARTMENTID)
)

INSERT INTO DEPARTMENT
VALUES('ADMIN','ADM','A-BLOCK'),
('COMPUTER','CE','C-BLOCK'),
('CIVIL','CI','G-BLOCK'),
('ELECTRICAL','EE','E-BLOCK'),
('MECHANICAL','ME','B-BLOCK'),
('CHEMICAL','CH','D-BLOCK')

SELECT * FROM DEPARTMENT

INSERT INTO PERSON
VALUES('RAHUL TRIPATHI',2,56000,'01-01-2000','RAJKOT'),
('HARDIK PANDYA',3,18000,'09-25-2001','AHMEDABAD'),
('BHAVIN KANANI',4,25000,'05-14-2000','BARODA'),
('BHOOMI VAISHNAV',1,39000,'02-08-2005','RAJKOT'),
('ROHIT TOPIYA',2,17000,'07-23-2001','JAMNAGAR'),
('PRIYA MENPARA',NULL,9000,'10-18-2000','AHMEDABAD'),
('NEHA SHARMA',2,34000,'12-25-2002','RAJKOT'),
('NAYAN GOSWAMI',3,25000,'07-01-2001','RAJKOT'),
('MEHUL BHUNDIYA',4,13500,'01-09-2005','BARODA'),
('MOHIT MARU',5,14000,'05-25-2000','JAMNAGAR')

SELECT * FROM PERSON

CREATE TABLE PUBLISHER
(
	PUBLISHERID INT PRIMARY KEY IDENTITY(1,1),
	PUBLISHERNAME VARCHAR(100) NOT NULL,
	CITY VARCHAR(50) NOT NULL

	CONSTRAINT UK_PULISHER_PUBLISHERNAME
	UNIQUE(PUBLISHERNAME)
)

CREATE TABLE AUTHOR
(
	AUTHORID INT PRIMARY KEY IDENTITY(1,1),
	AUTHORNAME VARCHAR(100) NOT NULL,
	COUNTRY VARCHAR(50)
)

CREATE TABLE BOOK
(
	BOOKID INT PRIMARY KEY IDENTITY(101,1),
	TITLE VARCHAR(200) NOT NULL,
	AUTHORID INT NOT NULL FOREIGN KEY REFERENCES AUTHOR(AUTHORID),
	PUBLISHERID INT NOT NULL FOREIGN KEY REFERENCES PUBLISHER(PUBLISHERID),
	PRICE DECIMAL(8,2) NOT NULL,
	PUBLICATIONYEAR INT NOT NULL
)


INSERT INTO PUBLISHER
VALUES('RUPA PUBLICATION','NEW DELHI'),
('PENGUIN INDIA','GURUGRAM'),
('HERPERCOLLINS INDIA','NOIDA'),
('PLEPH BOOK COMPANY','NEW DELHI')

SELECT * FROM PUBLISHER

INSERT INTO AUTHOR
VALUES('CHETAN BHAGAT','INDIA'),
('ARUNDHATI ROY','INDIA'),
('AMISH TRIPATHI','INDIA'),
('RUSKIN BOND','INDIA'),
('JHUMPA LAHIRI','INDIA'),
('PAULO COELHO','BRAZIL'),
('SUDHA MURTY','INDIA')

SELECT * FROM AUTHOR

INSERT INTO BOOK
VALUES('FIVE POINT SOMEONE',1,1,250,2004),
('THE GOD OF SMALL THINGS',2,2,350,1997),
('IMMORTALS OF MELUHA',3,3,300,2010),
('THE BLUE UMBRELLA',4,1,180,1980),
('THE LOWLAND',5,2,400,2013),
('REVOLUTION 2020',1,1,275,2011),
('SITA: WARRIOR OF MITHILA',3,2,320,2017),
('THE ROOM ON THE ROOF',4,4,200,1956)

SELECT * FROM BOOK

CREATE TABLE STADIUM
(
	STADIUM_IN INT PRIMARY KEY IDENTITY(101,1),
	STADIUM_NAME VARCHAR(200) NOT NULL UNIQUE,
	STADIUM_CAPACITY INT NOT NULL,
	STADIUM_CITY VARCHAR(200) NOT NULL
)

CREATE TABLE TEAM
(
	TEAM_ID INT PRIMARY KEY IDENTITY(101,1),
	TEAM_NAME VARCHAR(200) NOT NULL UNIQUE,
	TEAM_COACH VARCHAR(200) NOT NULL,
	TEAM_WINS INT NOT NULL,
	TEAM_TOTAL_MATCHES INT NULL,
	HOME_STADIUM_ID INT FOREIGN KEY REFERENCES STADIUM(STADIUM_ID)
)

CREATE TABLE PLAYER
(
	PLAYER_ID INT PRIMARY KEY IDENTITY(1,1),
	PLAYER_FIRST_NAME VARCHAR(200) NOT NULL,
	PLAYER_LAST_NAME VARCHAR(200) NOT NULL,
	TEAM_ID INT FOREIGN KEY REFERENCES TEAM(TEAM_ID),

)